### ISSUE TITLE
Gives out memory leak warnings.

### ISSUE THREAD

**Issue by kitsunde** [jbuck/wintersmith-nunjucks#14]
I get a few hundred of these at the start of running `wintersmith preview` on a project with around a 100 pages:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
  at StatWatcher.EventEmitter.addListener (events.js:160:15)
  at Object.fs.watchFile (fs.js:1162:8)
  at EventEmitter.FSWatcher._watch (/Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:239:8)
  at EventEmitter.FSWatcher._handleFile (/Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:263:8)
  at /Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:334:33
  at Object.oncomplete (fs.js:107:15)

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
  at StatWatcher.EventEmitter.addListener (events.js:160:15)
  at Object.fs.watchFile (fs.js:1162:8)
  at EventEmitter.FSWatcher._watch (/Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:239:8)
  at EventEmitter.FSWatcher._handleFile (/Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:263:8)
  at /Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:334:33
  at Object.oncomplete (fs.js:107:15)

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
  at StatWatcher.EventEmitter.addListener (events.js:160:15)
  at Object.fs.watchFile (fs.js:1162:8)
  at EventEmitter.FSWatcher._watch (/Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:239:8)
  at EventEmitter.FSWatcher._handleFile (/Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:263:8)
  at /Users/kitsunde/Development/navy-career/node_modules/wintersmith-nunjucks-content/node_modules/nunjucks/node_modules/chokidar/index.js:334:33
```

**Comment by jbuck** [comment]
Fixed in #15
